# Generated by Django 3.2.16 on 2023-05-05 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('globalwis', '0002_alter_stations_close_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_type',
        ),
        migrations.AlterField(
            model_name='stations',
            name='close_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 0, 49, 52, 484813, tzinfo=utc)),
        ),
    ]
